apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
spec:
  selector:
      matchLabels:
        app: application-db
  template:
    metadata:
      labels:
        app: application-db
    spec:
      containers:
      - name: k8s-demo
        image: naveen023/nodejs:1.0
        command: ["node", "index-db.js"]
        ports:
        - name: nodejs-port
          containerPort: 3000
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
        env:
          - name: MYSQL_HOST
            value: database-service
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: rootPassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: database
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-data
